//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThanhVien.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int DiemID { get; set; }
        public string MSSV { get; set; }
        public string ClassID { get; set; }
        public double DiemCK { get; set; }
        public double DiemGK { get; set; }
        public double DiemQT { get; set; }
    
        public virtual Lop Lop { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
