//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThanhVien.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int PhanHoiID { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> HoatDongID { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayPhanHoi { get; set; }
    
        public virtual HoatDong HoatDong { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
