//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThanhVien.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int ThanhToanID { get; set; }
        public string MSSV { get; set; }
        public decimal SoTien { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
